services:
  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        USERNAME: iw
    image: hpt:dev
    stdin_open: true
    tty: true
    container_name: hpt_dev
    shm_size: '16gb'          # ← 여기

    volumes:
      - .:/home/$USERNAME/hpt

    working_dir: /home/$USERNAME/hpt

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all